import Foundation

// This is authoritative static municipality data. Keeping the catalog intact
// makes updates auditable; splitting individual entries would fragment the source.
struct CommunityEventMunicipality: Identifiable, Hashable, Sendable {
    let code: String
    let name: String

    var id: String { code }
}

struct CommunityEventCounty: Identifiable, Hashable, Sendable {
    let code: String
    let name: String
    let municipalities: [CommunityEventMunicipality]

    var id: String { code }
}

// Official county and municipality codes from Statistics Norway's 2026 classification.
// swiftlint:disable:next type_body_length
enum CommunityEventLocationCatalog {
    static let counties: [CommunityEventCounty] = [
        CommunityEventCounty(
            code: "03", name: "Oslo",
            municipalities: [
                CommunityEventMunicipality(code: "0301", name: "Oslo - Oslove")
            ]),
        CommunityEventCounty(
            code: "11", name: "Rogaland",
            municipalities: [
                CommunityEventMunicipality(code: "1101", name: "Eigersund"),
                CommunityEventMunicipality(code: "1103", name: "Stavanger"),
                CommunityEventMunicipality(code: "1106", name: "Haugesund"),
                CommunityEventMunicipality(code: "1108", name: "Sandnes"),
                CommunityEventMunicipality(code: "1111", name: "Sokndal"),
                CommunityEventMunicipality(code: "1112", name: "Lund"),
                CommunityEventMunicipality(code: "1114", name: "Bjerkreim"),
                CommunityEventMunicipality(code: "1119", name: "Hå"),
                CommunityEventMunicipality(code: "1120", name: "Klepp"),
                CommunityEventMunicipality(code: "1121", name: "Time"),
                CommunityEventMunicipality(code: "1122", name: "Gjesdal"),
                CommunityEventMunicipality(code: "1124", name: "Sola"),
                CommunityEventMunicipality(code: "1127", name: "Randaberg"),
                CommunityEventMunicipality(code: "1130", name: "Strand"),
                CommunityEventMunicipality(code: "1133", name: "Hjelmeland"),
                CommunityEventMunicipality(code: "1134", name: "Suldal"),
                CommunityEventMunicipality(code: "1135", name: "Sauda"),
                CommunityEventMunicipality(code: "1144", name: "Kvitsøy"),
                CommunityEventMunicipality(code: "1145", name: "Bokn"),
                CommunityEventMunicipality(code: "1146", name: "Tysvær"),
                CommunityEventMunicipality(code: "1149", name: "Karmøy"),
                CommunityEventMunicipality(code: "1151", name: "Utsira"),
                CommunityEventMunicipality(code: "1160", name: "Vindafjord"),
            ]),
        CommunityEventCounty(
            code: "15", name: "Møre og Romsdal",
            municipalities: [
                CommunityEventMunicipality(code: "1505", name: "Kristiansund"),
                CommunityEventMunicipality(code: "1506", name: "Molde"),
                CommunityEventMunicipality(code: "1508", name: "Ålesund"),
                CommunityEventMunicipality(code: "1511", name: "Vanylven"),
                CommunityEventMunicipality(code: "1514", name: "Sande"),
                CommunityEventMunicipality(code: "1515", name: "Herøy (Møre og Romsdal)"),
                CommunityEventMunicipality(code: "1516", name: "Ulstein"),
                CommunityEventMunicipality(code: "1517", name: "Hareid"),
                CommunityEventMunicipality(code: "1520", name: "Ørsta"),
                CommunityEventMunicipality(code: "1525", name: "Stranda"),
                CommunityEventMunicipality(code: "1528", name: "Sykkylven"),
                CommunityEventMunicipality(code: "1531", name: "Sula"),
                CommunityEventMunicipality(code: "1532", name: "Giske"),
                CommunityEventMunicipality(code: "1535", name: "Vestnes"),
                CommunityEventMunicipality(code: "1539", name: "Rauma"),
                CommunityEventMunicipality(code: "1547", name: "Aukra"),
                CommunityEventMunicipality(code: "1554", name: "Averøy"),
                CommunityEventMunicipality(code: "1557", name: "Gjemnes"),
                CommunityEventMunicipality(code: "1560", name: "Tingvoll"),
                CommunityEventMunicipality(code: "1563", name: "Sunndal"),
                CommunityEventMunicipality(code: "1566", name: "Surnadal"),
                CommunityEventMunicipality(code: "1573", name: "Smøla"),
                CommunityEventMunicipality(code: "1576", name: "Aure"),
                CommunityEventMunicipality(code: "1577", name: "Volda"),
                CommunityEventMunicipality(code: "1578", name: "Fjord"),
                CommunityEventMunicipality(code: "1579", name: "Hustadvika"),
                CommunityEventMunicipality(code: "1580", name: "Haram"),
            ]),
        CommunityEventCounty(
            code: "18", name: "Nordland",
            municipalities: [
                CommunityEventMunicipality(code: "1804", name: "Bodø"),
                CommunityEventMunicipality(code: "1806", name: "Narvik"),
                CommunityEventMunicipality(code: "1811", name: "Bindal"),
                CommunityEventMunicipality(code: "1812", name: "Sømna"),
                CommunityEventMunicipality(code: "1813", name: "Brønnøy"),
                CommunityEventMunicipality(code: "1815", name: "Vega"),
                CommunityEventMunicipality(code: "1816", name: "Vevelstad"),
                CommunityEventMunicipality(code: "1818", name: "Herøy (Nordland)"),
                CommunityEventMunicipality(code: "1820", name: "Alstahaug"),
                CommunityEventMunicipality(code: "1822", name: "Leirfjord"),
                CommunityEventMunicipality(code: "1824", name: "Vefsn"),
                CommunityEventMunicipality(code: "1825", name: "Grane"),
                CommunityEventMunicipality(code: "1826", name: "Aarborte - Hattfjelldal"),
                CommunityEventMunicipality(code: "1827", name: "Dønna"),
                CommunityEventMunicipality(code: "1828", name: "Nesna"),
                CommunityEventMunicipality(code: "1832", name: "Hemnes"),
                CommunityEventMunicipality(code: "1833", name: "Rana - Raane"),
                CommunityEventMunicipality(code: "1834", name: "Lurøy"),
                CommunityEventMunicipality(code: "1835", name: "Træna"),
                CommunityEventMunicipality(code: "1836", name: "Rødøy"),
                CommunityEventMunicipality(code: "1837", name: "Meløy"),
                CommunityEventMunicipality(code: "1838", name: "Gildeskål"),
                CommunityEventMunicipality(code: "1839", name: "Beiarn"),
                CommunityEventMunicipality(code: "1840", name: "Saltdal"),
                CommunityEventMunicipality(code: "1841", name: "Fauske - Fuossko"),
                CommunityEventMunicipality(code: "1845", name: "Sørfold - Fuolldá"),
                CommunityEventMunicipality(code: "1848", name: "Steigen"),
                CommunityEventMunicipality(code: "1851", name: "Lødingen"),
                CommunityEventMunicipality(code: "1853", name: "Evenes - Evenášši"),
                CommunityEventMunicipality(code: "1856", name: "Røst"),
                CommunityEventMunicipality(code: "1857", name: "Værøy"),
                CommunityEventMunicipality(code: "1859", name: "Flakstad"),
                CommunityEventMunicipality(code: "1860", name: "Vestvågøy"),
                CommunityEventMunicipality(code: "1865", name: "Vågan"),
                CommunityEventMunicipality(code: "1866", name: "Hadsel"),
                CommunityEventMunicipality(code: "1867", name: "Bø"),
                CommunityEventMunicipality(code: "1868", name: "Øksnes"),
                CommunityEventMunicipality(code: "1870", name: "Sortland - Suortá"),
                CommunityEventMunicipality(code: "1871", name: "Andøy"),
                CommunityEventMunicipality(code: "1874", name: "Moskenes"),
                CommunityEventMunicipality(code: "1875", name: "Hábmer - Hamarøy"),
            ]),
        CommunityEventCounty(
            code: "31", name: "Østfold",
            municipalities: [
                CommunityEventMunicipality(code: "3101", name: "Halden"),
                CommunityEventMunicipality(code: "3103", name: "Moss"),
                CommunityEventMunicipality(code: "3105", name: "Sarpsborg"),
                CommunityEventMunicipality(code: "3107", name: "Fredrikstad"),
                CommunityEventMunicipality(code: "3110", name: "Hvaler"),
                CommunityEventMunicipality(code: "3112", name: "Råde"),
                CommunityEventMunicipality(code: "3114", name: "Våler (Østfold)"),
                CommunityEventMunicipality(code: "3116", name: "Skiptvet"),
                CommunityEventMunicipality(code: "3118", name: "Indre Østfold"),
                CommunityEventMunicipality(code: "3120", name: "Rakkestad"),
                CommunityEventMunicipality(code: "3122", name: "Marker"),
                CommunityEventMunicipality(code: "3124", name: "Aremark"),
            ]),
        CommunityEventCounty(
            code: "32", name: "Akershus",
            municipalities: [
                CommunityEventMunicipality(code: "3201", name: "Bærum"),
                CommunityEventMunicipality(code: "3203", name: "Asker"),
                CommunityEventMunicipality(code: "3205", name: "Lillestrøm"),
                CommunityEventMunicipality(code: "3207", name: "Nordre Follo"),
                CommunityEventMunicipality(code: "3209", name: "Ullensaker"),
                CommunityEventMunicipality(code: "3212", name: "Nesodden"),
                CommunityEventMunicipality(code: "3214", name: "Frogn"),
                CommunityEventMunicipality(code: "3216", name: "Vestby"),
                CommunityEventMunicipality(code: "3218", name: "Ås"),
                CommunityEventMunicipality(code: "3220", name: "Enebakk"),
                CommunityEventMunicipality(code: "3222", name: "Lørenskog"),
                CommunityEventMunicipality(code: "3224", name: "Rælingen"),
                CommunityEventMunicipality(code: "3226", name: "Aurskog-Høland"),
                CommunityEventMunicipality(code: "3228", name: "Nes"),
                CommunityEventMunicipality(code: "3230", name: "Gjerdrum"),
                CommunityEventMunicipality(code: "3232", name: "Nittedal"),
                CommunityEventMunicipality(code: "3234", name: "Lunner"),
                CommunityEventMunicipality(code: "3236", name: "Jevnaker"),
                CommunityEventMunicipality(code: "3238", name: "Nannestad"),
                CommunityEventMunicipality(code: "3240", name: "Eidsvoll"),
                CommunityEventMunicipality(code: "3242", name: "Hurdal"),
            ]),
        CommunityEventCounty(
            code: "33", name: "Buskerud",
            municipalities: [
                CommunityEventMunicipality(code: "3301", name: "Drammen"),
                CommunityEventMunicipality(code: "3303", name: "Kongsberg"),
                CommunityEventMunicipality(code: "3305", name: "Ringerike"),
                CommunityEventMunicipality(code: "3310", name: "Hole"),
                CommunityEventMunicipality(code: "3312", name: "Lier"),
                CommunityEventMunicipality(code: "3314", name: "Øvre Eiker"),
                CommunityEventMunicipality(code: "3316", name: "Modum"),
                CommunityEventMunicipality(code: "3318", name: "Krødsherad"),
                CommunityEventMunicipality(code: "3320", name: "Flå"),
                CommunityEventMunicipality(code: "3322", name: "Nesbyen"),
                CommunityEventMunicipality(code: "3324", name: "Gol"),
                CommunityEventMunicipality(code: "3326", name: "Hemsedal"),
                CommunityEventMunicipality(code: "3328", name: "Ål"),
                CommunityEventMunicipality(code: "3330", name: "Hol"),
                CommunityEventMunicipality(code: "3332", name: "Sigdal"),
                CommunityEventMunicipality(code: "3334", name: "Flesberg"),
                CommunityEventMunicipality(code: "3336", name: "Rollag"),
                CommunityEventMunicipality(code: "3338", name: "Nore og Uvdal"),
            ]),
        CommunityEventCounty(
            code: "34", name: "Innlandet",
            municipalities: [
                CommunityEventMunicipality(code: "3401", name: "Kongsvinger"),
                CommunityEventMunicipality(code: "3403", name: "Hamar"),
                CommunityEventMunicipality(code: "3405", name: "Lillehammer"),
                CommunityEventMunicipality(code: "3407", name: "Gjøvik"),
                CommunityEventMunicipality(code: "3411", name: "Ringsaker"),
                CommunityEventMunicipality(code: "3412", name: "Løten"),
                CommunityEventMunicipality(code: "3413", name: "Stange"),
                CommunityEventMunicipality(code: "3414", name: "Nord-Odal"),
                CommunityEventMunicipality(code: "3415", name: "Sør-Odal"),
                CommunityEventMunicipality(code: "3416", name: "Eidskog"),
                CommunityEventMunicipality(code: "3417", name: "Grue"),
                CommunityEventMunicipality(code: "3418", name: "Åsnes"),
                CommunityEventMunicipality(code: "3419", name: "Våler (Innlandet)"),
                CommunityEventMunicipality(code: "3420", name: "Elverum"),
                CommunityEventMunicipality(code: "3421", name: "Trysil"),
                CommunityEventMunicipality(code: "3422", name: "Åmot"),
                CommunityEventMunicipality(code: "3423", name: "Stor-Elvdal"),
                CommunityEventMunicipality(code: "3424", name: "Rendalen"),
                CommunityEventMunicipality(code: "3425", name: "Engerdal"),
                CommunityEventMunicipality(code: "3426", name: "Tolga"),
                CommunityEventMunicipality(code: "3427", name: "Tynset"),
                CommunityEventMunicipality(code: "3428", name: "Alvdal"),
                CommunityEventMunicipality(code: "3429", name: "Folldal"),
                CommunityEventMunicipality(code: "3430", name: "Os"),
                CommunityEventMunicipality(code: "3431", name: "Dovre"),
                CommunityEventMunicipality(code: "3432", name: "Lesja"),
                CommunityEventMunicipality(code: "3433", name: "Skjåk"),
                CommunityEventMunicipality(code: "3434", name: "Lom"),
                CommunityEventMunicipality(code: "3435", name: "Vågå"),
                CommunityEventMunicipality(code: "3436", name: "Nord-Fron"),
                CommunityEventMunicipality(code: "3437", name: "Sel"),
                CommunityEventMunicipality(code: "3438", name: "Sør-Fron"),
                CommunityEventMunicipality(code: "3439", name: "Ringebu"),
                CommunityEventMunicipality(code: "3440", name: "Øyer"),
                CommunityEventMunicipality(code: "3441", name: "Gausdal"),
                CommunityEventMunicipality(code: "3442", name: "Østre Toten"),
                CommunityEventMunicipality(code: "3443", name: "Vestre Toten"),
                CommunityEventMunicipality(code: "3446", name: "Gran"),
                CommunityEventMunicipality(code: "3447", name: "Søndre Land"),
                CommunityEventMunicipality(code: "3448", name: "Nordre Land"),
                CommunityEventMunicipality(code: "3449", name: "Sør-Aurdal"),
                CommunityEventMunicipality(code: "3450", name: "Etnedal"),
                CommunityEventMunicipality(code: "3451", name: "Nord-Aurdal"),
                CommunityEventMunicipality(code: "3452", name: "Vestre Slidre"),
                CommunityEventMunicipality(code: "3453", name: "Øystre Slidre"),
                CommunityEventMunicipality(code: "3454", name: "Vang"),
            ]),
        CommunityEventCounty(
            code: "39", name: "Vestfold",
            municipalities: [
                CommunityEventMunicipality(code: "3901", name: "Horten"),
                CommunityEventMunicipality(code: "3903", name: "Holmestrand"),
                CommunityEventMunicipality(code: "3905", name: "Tønsberg"),
                CommunityEventMunicipality(code: "3907", name: "Sandefjord"),
                CommunityEventMunicipality(code: "3909", name: "Larvik"),
                CommunityEventMunicipality(code: "3911", name: "Færder"),
            ]),
        CommunityEventCounty(
            code: "40", name: "Telemark",
            municipalities: [
                CommunityEventMunicipality(code: "4001", name: "Porsgrunn"),
                CommunityEventMunicipality(code: "4003", name: "Skien"),
                CommunityEventMunicipality(code: "4005", name: "Notodden"),
                CommunityEventMunicipality(code: "4010", name: "Siljan"),
                CommunityEventMunicipality(code: "4012", name: "Bamble"),
                CommunityEventMunicipality(code: "4014", name: "Kragerø"),
                CommunityEventMunicipality(code: "4016", name: "Drangedal"),
                CommunityEventMunicipality(code: "4018", name: "Nome"),
                CommunityEventMunicipality(code: "4020", name: "Midt-Telemark"),
                CommunityEventMunicipality(code: "4022", name: "Seljord"),
                CommunityEventMunicipality(code: "4024", name: "Hjartdal"),
                CommunityEventMunicipality(code: "4026", name: "Tinn"),
                CommunityEventMunicipality(code: "4028", name: "Kviteseid"),
                CommunityEventMunicipality(code: "4030", name: "Nissedal"),
                CommunityEventMunicipality(code: "4032", name: "Fyresdal"),
                CommunityEventMunicipality(code: "4034", name: "Tokke"),
                CommunityEventMunicipality(code: "4036", name: "Vinje"),
            ]),
        CommunityEventCounty(
            code: "42", name: "Agder",
            municipalities: [
                CommunityEventMunicipality(code: "4201", name: "Risør"),
                CommunityEventMunicipality(code: "4202", name: "Grimstad"),
                CommunityEventMunicipality(code: "4203", name: "Arendal"),
                CommunityEventMunicipality(code: "4204", name: "Kristiansand"),
                CommunityEventMunicipality(code: "4205", name: "Lindesnes"),
                CommunityEventMunicipality(code: "4206", name: "Farsund"),
                CommunityEventMunicipality(code: "4207", name: "Flekkefjord"),
                CommunityEventMunicipality(code: "4211", name: "Gjerstad"),
                CommunityEventMunicipality(code: "4212", name: "Vegårshei"),
                CommunityEventMunicipality(code: "4213", name: "Tvedestrand"),
                CommunityEventMunicipality(code: "4214", name: "Froland"),
                CommunityEventMunicipality(code: "4215", name: "Lillesand"),
                CommunityEventMunicipality(code: "4216", name: "Birkenes"),
                CommunityEventMunicipality(code: "4217", name: "Åmli"),
                CommunityEventMunicipality(code: "4218", name: "Iveland"),
                CommunityEventMunicipality(code: "4219", name: "Evje og Hornnes"),
                CommunityEventMunicipality(code: "4220", name: "Bygland"),
                CommunityEventMunicipality(code: "4221", name: "Valle"),
                CommunityEventMunicipality(code: "4222", name: "Bykle"),
                CommunityEventMunicipality(code: "4223", name: "Vennesla"),
                CommunityEventMunicipality(code: "4224", name: "Åseral"),
                CommunityEventMunicipality(code: "4225", name: "Lyngdal"),
                CommunityEventMunicipality(code: "4226", name: "Hægebostad"),
                CommunityEventMunicipality(code: "4227", name: "Kvinesdal"),
                CommunityEventMunicipality(code: "4228", name: "Sirdal"),
            ]),
        CommunityEventCounty(
            code: "46", name: "Vestland",
            municipalities: [
                CommunityEventMunicipality(code: "4601", name: "Bergen"),
                CommunityEventMunicipality(code: "4602", name: "Kinn"),
                CommunityEventMunicipality(code: "4611", name: "Etne"),
                CommunityEventMunicipality(code: "4612", name: "Sveio"),
                CommunityEventMunicipality(code: "4613", name: "Bømlo"),
                CommunityEventMunicipality(code: "4614", name: "Stord"),
                CommunityEventMunicipality(code: "4615", name: "Fitjar"),
                CommunityEventMunicipality(code: "4616", name: "Tysnes"),
                CommunityEventMunicipality(code: "4617", name: "Kvinnherad"),
                CommunityEventMunicipality(code: "4618", name: "Ullensvang"),
                CommunityEventMunicipality(code: "4619", name: "Eidfjord"),
                CommunityEventMunicipality(code: "4620", name: "Ulvik"),
                CommunityEventMunicipality(code: "4621", name: "Voss"),
                CommunityEventMunicipality(code: "4622", name: "Kvam"),
                CommunityEventMunicipality(code: "4623", name: "Samnanger"),
                CommunityEventMunicipality(code: "4624", name: "Bjørnafjorden"),
                CommunityEventMunicipality(code: "4625", name: "Austevoll"),
                CommunityEventMunicipality(code: "4626", name: "Øygarden"),
                CommunityEventMunicipality(code: "4627", name: "Askøy"),
                CommunityEventMunicipality(code: "4628", name: "Vaksdal"),
                CommunityEventMunicipality(code: "4629", name: "Modalen"),
                CommunityEventMunicipality(code: "4630", name: "Osterøy"),
                CommunityEventMunicipality(code: "4631", name: "Alver"),
                CommunityEventMunicipality(code: "4632", name: "Austrheim"),
                CommunityEventMunicipality(code: "4633", name: "Fedje"),
                CommunityEventMunicipality(code: "4634", name: "Masfjorden"),
                CommunityEventMunicipality(code: "4635", name: "Gulen"),
                CommunityEventMunicipality(code: "4636", name: "Solund"),
                CommunityEventMunicipality(code: "4637", name: "Hyllestad"),
                CommunityEventMunicipality(code: "4638", name: "Høyanger"),
                CommunityEventMunicipality(code: "4639", name: "Vik"),
                CommunityEventMunicipality(code: "4640", name: "Sogndal"),
                CommunityEventMunicipality(code: "4641", name: "Aurland"),
                CommunityEventMunicipality(code: "4642", name: "Lærdal"),
                CommunityEventMunicipality(code: "4643", name: "Årdal"),
                CommunityEventMunicipality(code: "4644", name: "Luster"),
                CommunityEventMunicipality(code: "4645", name: "Askvoll"),
                CommunityEventMunicipality(code: "4646", name: "Fjaler"),
                CommunityEventMunicipality(code: "4647", name: "Sunnfjord"),
                CommunityEventMunicipality(code: "4648", name: "Bremanger"),
                CommunityEventMunicipality(code: "4649", name: "Stad"),
                CommunityEventMunicipality(code: "4650", name: "Gloppen"),
                CommunityEventMunicipality(code: "4651", name: "Stryn"),
            ]),
        CommunityEventCounty(
            code: "50", name: "Trøndelag",
            municipalities: [
                CommunityEventMunicipality(code: "5001", name: "Trondheim - Tråante"),
                CommunityEventMunicipality(code: "5006", name: "Steinkjer - Stïentje"),
                CommunityEventMunicipality(code: "5007", name: "Namsos - Nåavmesjenjaelmie"),
                CommunityEventMunicipality(code: "5014", name: "Frøya"),
                CommunityEventMunicipality(code: "5020", name: "Osen"),
                CommunityEventMunicipality(code: "5021", name: "Oppdal"),
                CommunityEventMunicipality(code: "5022", name: "Rennebu"),
                CommunityEventMunicipality(code: "5025", name: "Røros - Rosse"),
                CommunityEventMunicipality(code: "5026", name: "Holtålen"),
                CommunityEventMunicipality(code: "5027", name: "Midtre Gauldal"),
                CommunityEventMunicipality(code: "5028", name: "Melhus"),
                CommunityEventMunicipality(code: "5029", name: "Skaun"),
                CommunityEventMunicipality(code: "5031", name: "Malvik"),
                CommunityEventMunicipality(code: "5032", name: "Selbu"),
                CommunityEventMunicipality(code: "5033", name: "Tydal"),
                CommunityEventMunicipality(code: "5034", name: "Meråker"),
                CommunityEventMunicipality(code: "5035", name: "Stjørdal"),
                CommunityEventMunicipality(code: "5036", name: "Frosta"),
                CommunityEventMunicipality(code: "5037", name: "Levanger - Levangke"),
                CommunityEventMunicipality(code: "5038", name: "Verdal"),
                CommunityEventMunicipality(code: "5041", name: "Snåase - Snåsa"),
                CommunityEventMunicipality(code: "5042", name: "Lierne"),
                CommunityEventMunicipality(code: "5043", name: "Raarvihke - Røyrvik"),
                CommunityEventMunicipality(code: "5044", name: "Namsskogan"),
                CommunityEventMunicipality(code: "5045", name: "Grong"),
                CommunityEventMunicipality(code: "5046", name: "Høylandet"),
                CommunityEventMunicipality(code: "5047", name: "Overhalla"),
                CommunityEventMunicipality(code: "5049", name: "Flatanger"),
                CommunityEventMunicipality(code: "5052", name: "Leka"),
                CommunityEventMunicipality(code: "5053", name: "Inderøy"),
                CommunityEventMunicipality(code: "5054", name: "Indre Fosen"),
                CommunityEventMunicipality(code: "5055", name: "Heim"),
                CommunityEventMunicipality(code: "5056", name: "Hitra"),
                CommunityEventMunicipality(code: "5057", name: "Ørland"),
                CommunityEventMunicipality(code: "5058", name: "Åfjord"),
                CommunityEventMunicipality(code: "5059", name: "Orkland"),
                CommunityEventMunicipality(code: "5060", name: "Nærøysund"),
                CommunityEventMunicipality(code: "5061", name: "Rindal"),
            ]),
        CommunityEventCounty(
            code: "55", name: "Troms",
            municipalities: [
                CommunityEventMunicipality(code: "5501", name: "Tromsø"),
                CommunityEventMunicipality(code: "5503", name: "Harstad - Hárstták"),
                CommunityEventMunicipality(code: "5510", name: "Kvæfjord"),
                CommunityEventMunicipality(code: "5512", name: "Dielddanuorri - Tjeldsund"),
                CommunityEventMunicipality(code: "5514", name: "Ibestad"),
                CommunityEventMunicipality(code: "5516", name: "Gratangen - Rivtták"),
                CommunityEventMunicipality(code: "5518", name: "Loabák - Lavangen"),
                CommunityEventMunicipality(code: "5520", name: "Bardu"),
                CommunityEventMunicipality(code: "5522", name: "Salangen"),
                CommunityEventMunicipality(code: "5524", name: "Målselv"),
                CommunityEventMunicipality(code: "5526", name: "Sørreisa"),
                CommunityEventMunicipality(code: "5528", name: "Dyrøy"),
                CommunityEventMunicipality(code: "5530", name: "Senja"),
                CommunityEventMunicipality(code: "5532", name: "Balsfjord"),
                CommunityEventMunicipality(code: "5534", name: "Karlsøy"),
                CommunityEventMunicipality(code: "5536", name: "Lyngen - Ivgu - Yykeä"),
                CommunityEventMunicipality(code: "5538", name: "Storfjord - Omasvuotna - Omasvuono"),
                CommunityEventMunicipality(code: "5540", name: "Gáivuotna - Kåfjord - Kaivuono"),
                CommunityEventMunicipality(code: "5542", name: "Skjervøy"),
                CommunityEventMunicipality(code: "5544", name: "Nordreisa - Ráisa - Raisi"),
                CommunityEventMunicipality(code: "5546", name: "Kvænangen"),
            ]),
        CommunityEventCounty(
            code: "56", name: "Finnmark",
            municipalities: [
                CommunityEventMunicipality(code: "5601", name: "Alta"),
                CommunityEventMunicipality(code: "5603", name: "Hammerfest - Hámmerfeasta"),
                CommunityEventMunicipality(code: "5605", name: "Sør-Varanger"),
                CommunityEventMunicipality(code: "5607", name: "Vadsø"),
                CommunityEventMunicipality(code: "5610", name: "Kárášjohka - Karasjok"),
                CommunityEventMunicipality(code: "5612", name: "Guovdageaidnu - Kautokeino"),
                CommunityEventMunicipality(code: "5614", name: "Loppa"),
                CommunityEventMunicipality(code: "5616", name: "Hasvik"),
                CommunityEventMunicipality(code: "5618", name: "Måsøy"),
                CommunityEventMunicipality(code: "5620", name: "Nordkapp"),
                CommunityEventMunicipality(code: "5622", name: "Porsanger - Porsángu - Porsanki"),
                CommunityEventMunicipality(code: "5624", name: "Lebesby"),
                CommunityEventMunicipality(code: "5626", name: "Gamvik"),
                CommunityEventMunicipality(code: "5628", name: "Deatnu - Tana"),
                CommunityEventMunicipality(code: "5630", name: "Berlevåg"),
                CommunityEventMunicipality(code: "5632", name: "Båtsfjord"),
                CommunityEventMunicipality(code: "5634", name: "Vardø"),
                CommunityEventMunicipality(code: "5636", name: "Unjárga - Nesseby"),
            ]),
    ]

    static var allMunicipalities: [CommunityEventMunicipality] {
        counties.flatMap(\.municipalities)
    }

    static func county(for municipalityCode: String?) -> CommunityEventCounty? {
        guard let municipalityCode else { return nil }
        return counties.first { $0.municipalities.contains { $0.code == municipalityCode } }
    }

    static func municipality(for code: String?) -> CommunityEventMunicipality? {
        guard let code else { return nil }
        return allMunicipalities.first { $0.code == code }
    }

    // swiftlint:disable:next file_length
}
