-- Keep untrusted API clients on the narrowest write path. RLS still binds
-- caller-owned identities, while server-managed status, moderation, and
-- relationship transitions are handled by the existing RPCs.

-- RSVP visibility, capacity, group membership, and status validation belong in
-- set_community_event_rsvp(), not in a direct table mutation.
revoke insert, update, delete on public.community_event_rsvps from anon, authenticated;

-- Event and group lifecycle changes already use security-definer RPCs.
revoke insert, update, delete on public.community_events from anon, authenticated;

-- Join-request status/reviewer fields are server-managed. Cancellation remains
-- a direct delete restricted by the existing pending-request RLS policy.
revoke insert, update, delete on public.community_group_join_requests from anon, authenticated;
grant delete on public.community_group_join_requests to authenticated;

-- Group membership roles are never client-updatable. Public-group joining keeps
-- its existing RLS-protected insert path; leaving remains a direct delete.
revoke update on public.community_group_memberships from anon, authenticated;
revoke insert on public.community_group_memberships from anon, authenticated;
grant insert (group_id, user_id, role) on public.community_group_memberships to authenticated;
grant delete on public.community_group_memberships to authenticated;

-- Follow/block identity columns are caller-bound by RLS and are not mutable
-- after insertion. Keep the existing direct insert/delete UX paths.
revoke update on public.community_follows from anon, authenticated;
revoke insert on public.community_follows from anon, authenticated;
grant insert (follower_id, following_id) on public.community_follows to authenticated;

revoke update on public.user_blocks from anon, authenticated;
revoke insert on public.user_blocks from anon, authenticated;
grant insert (blocker_id, blocked_user_id) on public.user_blocks to authenticated;

-- A member may edit post content only. Author, group, moderation state, and
-- timestamps remain outside the client update surface.
revoke insert, update, delete on public.community_posts from anon;
revoke update on public.community_posts from anon, authenticated;
grant update (title, body, kind) on public.community_posts to authenticated;

-- A member may edit comment content only. Author, post association,
-- moderation state, and timestamps remain server-controlled.
revoke insert, update, delete on public.community_comments from anon;
revoke update on public.community_comments from anon, authenticated;
grant update (body) on public.community_comments to authenticated;

-- Notifications are generated by server-side triggers/RPCs. A recipient may
-- only acknowledge read state; actor, recipient, type, target, and event
-- metadata cannot be rewritten by the client.
revoke insert, update, delete on public.community_notifications from anon;
revoke update on public.community_notifications from anon, authenticated;
grant update (read_at) on public.community_notifications to authenticated;

-- Reports may be submitted by the client, but review state and reviewer data
-- are server-managed. reporter_id remains present so the existing RLS policy
-- can bind it to auth.uid(); all moderation columns are excluded from INSERT.
revoke insert, update, delete on public.community_reports from anon, authenticated;
grant insert (reporter_id, target_type, target_id, reason, details)
  on public.community_reports to authenticated;

-- Moderation and cleanup records are never client-authored or client-mutated.
revoke insert, update, delete on public.community_group_bans from anon, authenticated;
revoke insert, update, delete on public.community_group_moderation_audit from anon, authenticated;
revoke insert, update, delete on public.community_group_removed_post_media from anon, authenticated;
revoke insert, update, delete on public.community_member_restrictions from anon, authenticated;
revoke insert, update, delete on public.community_moderation_action_audit from anon, authenticated;
revoke insert, update, delete on public.community_moderation_review_audit from anon, authenticated;
